#ifndef PIN_DEFINITIONS_H
#define PIN_DEFINITIONS_H

#include <DHT.h>

#define USER_INPUT_PIN_1 3
#define USER_INPUT_PIN_2 5
#define SD_CS_PIN 49
#define NOISE_PIN 6
#define DHT_PIN 2
#define DHT_TYPE DHT22
#define AIR_QUAL_PIN 8
#define BUZZER_PIN 9
#define CO2_PWM_PIN 10
#define NOISE_SENSOR_A_PIN 0


#define UV_INTENSITY_PIN -1
#define LIGHT_INTENSITY_PIN -1
#define CO2_AMMOUNT_PIN -1
#define SMOKE_AMMOUNT_PIN -1
#define SOUND_PRESSURE_PIN -1

#endif // PIN_DEFINITIONS_H
